### ISSUE TITLE
ClassNotFoundException: ContainerDelegateImpl

### ISSUE THREAD

**Issue by jimmysuncpt** [zhihu/SugarAdapter#7]
异常信息如下：
```
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.zhihu.android.sugaradapter.ContainerDelegateImpl
    at com.zhihu.android.sugaradapter.Sugar.getContainerDelegate(Sugar.java:38)
    at com.zhihu.android.sugaradapter.SugarAdapter$Builder.add(SugarAdapter.java:63)
    at com.zhihu.android.sugaradapter.SugarAdapter$Builder.add(SugarAdapter.java:57)
    ...
```
请问如何解决？

**Comment by mthli** [comment]
按照 [README](https://github.com/zhihu/SugarAdapter/blob/master/README_zh_CN.md#gradle) 正确配置即可。

**Comment by jimmysuncpt** [comment]
我知道了，需要在主工程至少实现一个 holder，如果没有的话就建一个空的 holder。
